name: Deploy Backend Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Nest.js App
        run: yarn build
